/**
 * Big Block Audio
 * Copyright (C) 2011 Foldi, LLC
 * Licensed under the MIT license.
 *
 * Provides an interface to play audio files in an HTML 5 compliant web browser.
 * 
 * @author Vince Allen 01-01-2011
 * 
 * version 1.0
 */
function f(o){throw o;}var i=true,m=false;
(function(o){o.F.C=function(u){var s,j;s={m:o("#bigblockaudio_debug_messages"),f:m,e:m,i:i,filename:m,n:500,g:["wav","mp3","ogg"],k:{},l:null,e:null};j=o.extend(s,u);return this.D(function(){BigBlockAudio=function(){var r,q;r=function(b){try{if(BigBlockAudio.m)BigBlockAudio.m.append(b+"\n");else if(typeof console!=="undefined")console.log(b);else typeof opera!=="undefined"&&opera.postError(b)}catch(c){}};q=i;if(typeof window.B==="undefined"){q=m;r("This browser does not support HTML5 audio.")}return{m:j.m,f:j.f,
e:j.e,i:j.i,filename:j.filename,g:j.g,k:j.k,n:j.n,l:j.l,e:j.e,P:navigator.userAgent.toLowerCase(),d:q,a:{},z:null,v:(new Date).getTime(),muted:m,j:[],p:m,add:function(b,c,d,e){var h,g,k,l,n;if(q){try{if(typeof b==="undefined")f(Error("An id is required"));if(typeof c==="undefined")f(Error("Path to audio file required"))}catch(t){BigBlockAudio.b(t.name+": "+t.message)}typeof this.l==="function"&&this.l(b);for(h=0;h<this.g.length;h++){k=BigBlockAudio.r(this.g[h]);n=new Audio(c+b+"."+this.g[h]);n.L=
"metadata";n.autoplay=m;if(d)n.loop=d;l="";for(g=0;g<k.length;g++){l=this.canPlayType(n,k[g]);if(l!==""){this.f&&BigBlockAudio.b("This browser will try to play "+b+" audio file in "+k[g]+" format.");break}}if(l!=="")break}if(l!==""){n.id=b;this.a[b]=n;g=this.a[b];if(g.addEventListener){g.addEventListener("loadeddata",function(p){e&&typeof e==="function"?BigBlockAudio.c(p,e(p)):BigBlockAudio.c(p)},m);g.addEventListener("loadstart",BigBlockAudio.c,m);g.addEventListener("progress",BigBlockAudio.c,m);
g.addEventListener("suspend",BigBlockAudio.c,m);g.addEventListener("abort",BigBlockAudio.c,m);g.addEventListener("error",BigBlockAudio.c,m);g.addEventListener("emptied",BigBlockAudio.c,m);g.addEventListener("stalled",BigBlockAudio.c,m)}else if(a.attachEvent){g.attachEvent("loadeddata",function(p){BigBlockAudio.c(p,e)},m);g.attachEvent("loadstart",BigBlockAudio.c,m);g.attachEvent("progress",BigBlockAudio.c,m);g.attachEvent("suspend",BigBlockAudio.c,m);g.attachEvent("abort",BigBlockAudio.c,m);g.attachEvent("error",
BigBlockAudio.c,m);g.attachEvent("emptied",BigBlockAudio.c,m);g.attachEvent("stalled",BigBlockAudio.c,m)}if(g.load){this.j.push(b);this.w(b)}else{this.d=m;this.a=[];BigBlockAudio.b("This browser does not support HTML5 audio.")}}else{BigBlockAudio.b("Audio mime-type "+k+" not supported. "+this.g+" files will not be played.");if(BigBlockAudio.i){BigBlockAudio.d=m;BigBlockAudio.a=[]}}}},c:function(b,c){var d,e;e="An audio event ("+b.type+") for "+b.target.id+" just fired.";switch(b.type){case "loadstart":e=
"BigBlockAudio: eventHandler: Audio file "+b.target.id+" has started loading.";break;case "progress":e="BigBlockAudio: eventHandler: Audio file "+b.target.id+" is loading.";break;case "suspend":e="BigBlockAudio: eventHandler: The user agent is intentionally not currently fetching "+b.target.id+", but does not have the entire media resource downloaded.";break;case "abort":e="BigBlockAudio: eventHandler: The user agent stopped fetching "+b.target.id+" before it was completely downloaded, but not due to an error.";
break;case "error":e="BigBlockAudio: eventHandler: An error occurred while fetching "+b.target.id+".";if(BigBlockAudio.i){BigBlockAudio.d=m;BigBlockAudio.a=[]}break;case "emptied":e="BigBlockAudio: eventHandler: "+b.target.id+"'s network state just switched to NETWORK_EMPTY.";break;case "stalled":e="BigBlockAudio: eventHandler: The user agent is trying to fetch "+b.target.id+", but data is unexpectedly not forthcoming.";break;case "loadeddata":if(!BigBlockAudio.a[b.target.id].loaded){e="BigBlockAudio: eventHandler: Audio file "+
b.target.id+" is ready to play.";typeof c==="function"&&!BigBlockAudio.p&&setTimeout(function(){c()},0);BigBlockAudio.a[b.target.id].loaded=i}}if(b.type!=="loadstart"&&b.type!=="progress"&&b.type!=="suspend"&&b.type!=="emptied"&&b.type!=="stalled"){if(!BigBlockAudio.p)for(d=0;d<BigBlockAudio.j.length;d++)if(BigBlockAudio.j[d]===b.target.id){BigBlockAudio.j.splice(d,1);if(BigBlockAudio.j.length<1){BigBlockAudio.p=i;BigBlockAudio.e&&typeof BigBlockAudio.e==="function"&&BigBlockAudio.e()}break}if(BigBlockAudio.a[b.target.id]){BigBlockAudio.a[b.target.id].removeEventListener("loadeddata",
this.c,m);BigBlockAudio.a[b.target.id].removeEventListener("loadstart",this.c,m);BigBlockAudio.a[b.target.id].removeEventListener("progress",this.c,m);BigBlockAudio.a[b.target.id].removeEventListener("suspend",this.c,m);BigBlockAudio.a[b.target.id].removeEventListener("abort",this.c,m);BigBlockAudio.a[b.target.id].removeEventListener("error",this.c,m);BigBlockAudio.a[b.target.id].removeEventListener("emptied",this.c,m);BigBlockAudio.a[b.target.id].removeEventListener("stalled",this.c,m)}}BigBlockAudio.f===
i&&BigBlockAudio.b(e)},canPlayType:function(b,c){try{if(typeof c==="undefined")f(Error("A type is required"))}catch(d){BigBlockAudio.b(d.name+": "+d.message)}try{return b.canPlayType?b.canPlayType(c):"maybe"}catch(e){BigBlockAudio.b(e.name+": "+e.message)}return m},w:function(b){if(typeof this.a[b]!=="undefined"&&this.d){try{if(typeof b==="undefined")f(Error("An id is required"))}catch(c){BigBlockAudio.b(c.name+": "+c.message)}try{this.a[b].load()}catch(d){BigBlockAudio.b(d.name+": "+d.message)}}},
play:function(b,c,d){var e,h,g;if(this.d){try{if(typeof b==="undefined")f(Error("An id is required"))}catch(k){BigBlockAudio.b(k.name+": "+k.message)}try{if(this.i){if(typeof this.a[this.filename]!=="undefined"){g=this.o(this.filename,i);this.f&&BigBlockAudio.b("Audio: State: "+g.h+" Message: "+g.message);if(g.h===4&&this.muted===m){e=this.k[b].N/1E3;h=this.k[b].duration>this.n?this.k[b].duration:this.n;this.pause(this.filename);this.A(this.filename,e);c&&typeof c==="function"&&c();this.a[this.filename].play();
this.v=void 0;this.z=setTimeout(function(){BigBlockAudio.pause(BigBlockAudio.filename);d&&typeof d==="function"&&d()},h)}}}else if(typeof this.a[b]!=="undefined"){g=this.o(b,this.f);this.f&&BigBlockAudio.b("Audio: State: "+g.h+" Message: "+g.message);if(g.h>=2&&this.muted===m){typeof c!=="undefined"&&c();if(typeof d!=="undefined"){h=this.q(b)*1E3;setTimeout(function(){d()},h)}this.a[b].pause();this.a[b].play()}}}catch(l){BigBlockAudio.b(l.name+": "+l.message)}}},pause:function(b,c){if(typeof this.a[b]!==
"undefined"&&this.d){try{if(typeof b==="undefined")f(Error("An id is required"))}catch(d){BigBlockAudio.b(d.name+": "+d.message)}var e=this.o(b,i);if(e.h>2)if(typeof c!=="undefined")if(this.u(b)===m)try{this.a[b].pause()}catch(h){BigBlockAudio.b(h.name+": "+h.message)}else{e=this.s(b);var g=this.t(b);if(e.length>0&&g!==i)try{this.a[b].play()}catch(k){BigBlockAudio.b(k.name+": "+k.message)}}else try{this.a[b].pause()}catch(l){BigBlockAudio.b(l.name+": "+l.message)}else BigBlockAudio.b("Audio: "+e.message)}},
u:function(b){if(typeof this.a[b]!=="undefined"&&this.d){try{if(typeof b==="undefined")f(Error("An id is required"))}catch(c){BigBlockAudio.b(c.name+": "+c.message)}try{return this.a[b].paused}catch(d){BigBlockAudio.b(d.name+": "+d.message)}}},s:function(b){if(typeof this.a[b]!=="undefined"&&this.d){try{if(typeof b==="undefined")f(Error("An id is required"))}catch(c){BigBlockAudio.b(c.name+": "+c.message)}try{return this.a[b].played}catch(d){BigBlockAudio.b(d.name+": "+d.message)}}},t:function(b){if(typeof this.a[b]!==
"undefined"&&this.d){try{if(typeof b==="undefined")f(Error("An id is required"))}catch(c){BigBlockAudio.b(c.name+": "+c.message)}try{return this.a[b].ended}catch(d){BigBlockAudio.b(d.name+": "+d.message)}}},I:function(b){if(typeof this.a[b]!=="undefined"&&this.d){try{if(typeof b==="undefined")f(Error("An id is required"))}catch(c){BigBlockAudio.b(c.name+": "+c.message)}try{return this.a[b].playbackRate}catch(d){BigBlockAudio.b(d.name+": "+d.message)}}},o:function(b,c){if(typeof this.a[b]!=="undefined"&&
this.d){try{if(typeof b==="undefined")f(Error("An id is required"))}catch(d){BigBlockAudio.b(d.name+": "+d.message)}var e=this.a[b].readyState;if(typeof c!=="undefined"){var h;switch(e){case 0:h="HAVE_NOTHING: No data for the current playback position is available.";break;case 1:h="HAVE_METADATA : Enough of the resource has been obtained that the duration of the resource is available. No media data is available for the immediate current playback position.";break;case 2:h="HAVE_CURRENT_DATA: Data for the immediate current playback position is available, but not enough data is available to successfully advance the current playback position in the direction of playback.";
break;case 3:h="HAVE_FUTURE_DATA: Data for the immediate current playback position is available. However, not enough data is avaialble to determine if playback will out-pace the data stream.";break;case 4:h="HAVE_ENOUGH_DATA: All data for the immediate current playback position is available."}e={h:e,message:h}}else e=e;return e}},H:function(b,c){if(typeof this.a[b]!=="undefined"&&this.d){try{if(typeof b==="undefined")f(Error("An id is required"))}catch(d){BigBlockAudio.b(d.name+": "+d.message)}var e=
this.a[b].networkState;if(typeof c!=="undefined"){var h;switch(e){case 0:h="NETWORK_EMPTY: The element has not yet been initialized. All attributes are in their initial states.";break;case 1:h="NETWORK_IDLE: The element's resource selection algorithm is active and has selected a resource, but it is not actually using the network at this time.";break;case 2:h="NETWORK_LOADING: The user agent is actively trying to download data.";break;case 3:h="NETWORK_NO_SOURCE: The element's resource selection algorithm is active, but it has so not yet found a resource to use."}e=
{h:e,message:h}}else e=e;return e}},q:function(b){if(typeof this.a[b]!=="undefined"&&this.d){try{if(typeof b==="undefined")f(Error("An id is required"))}catch(c){BigBlockAudio.b(c.name+": "+c.message)}try{return this.a[b].duration}catch(d){BigBlockAudio.b(d.name+": "+d.message)}}},G:function(b){if(typeof this.a[b]!=="undefined"&&this.d){try{if(typeof b==="undefined")f(Error("An id is required"))}catch(c){BigBlockAudio.b(c.name+": "+c.message)}try{return this.a[b].currentTime}catch(d){BigBlockAudio.b(d.name+
": "+d.message)}}},A:function(b,c){if(typeof this.a[b]!=="undefined"&&this.d){try{if(typeof b==="undefined")f(Error("An id is required"))}catch(d){BigBlockAudio.b(d.name+": "+d.message)}try{this.a[b].currentTime=c}catch(e){BigBlockAudio.b(e.name+": "+e.message)}}},J:function(b){if(typeof this.a[b]!=="undefined"&&this.d){try{if(typeof b==="undefined")f(Error("An id is required"))}catch(c){BigBlockAudio.b(c.name+": "+c.message)}try{return this.a[b].volume}catch(d){BigBlockAudio.b(d.name+": "+d.message)}}},
M:function(b,c){if(typeof this.a[b]!=="undefined"&&this.d){try{if(typeof b==="undefined")f(Error("An id is required"));if(typeof c==="undefined")f(Error("A volume value between 0.0 and 1.0 is required"))}catch(d){BigBlockAudio.b(d.name+": "+d.message)}try{this.a[b].volume=c}catch(e){BigBlockAudio.b(e.name+": "+e.message)}}},K:function(){var b;if(this.d){for(b in this.a)if(this.a.hasOwnProperty(b))try{this.a[b].muted=i}catch(c){BigBlockAudio.b(c.name+": "+c.message)}this.muted=i}},O:function(){var b;
if(this.d){for(b in this.a)if(this.a.hasOwnProperty(b))try{this.a[b].muted=m}catch(c){BigBlockAudio.b(c.name+": "+c.message)}this.muted=m}},b:r,r:function(b){try{if(typeof b==="undefined")f(Error("BigBlock.getMimeTypeFromFileExt(ext): An extension is required."));else switch(b){case "aif":return["audio/x-aiff","audio/x-aiff"];case "au":case "snd":return["audio/basic"];case "ogg":return["audio/ogg"];case "mp3":return["audio/mpeg","audio/x-mpeg"];case "wav":return["audio/wav","audio/x-wav"];default:return m}}catch(c){BigBlock.b.display(c.name+
": "+c.message)}}}}()})}})(jQuery);